environment: ubuntu1404-node
modes:
  prod: [dev, beta, prod]
prepare:
  - sudo apt-get update && sudo apt-get install --yes build-essential libstdc++6 automake

build:
  - make deps
  - make
  - cd /build/withings-sas/corvus; tar czf ../../corvus.tgz src/corvus
publish: /build/corvus.tgz
